Desafio Java
ilegra/mais-pra-ti pull request #17
Opened 2021-02-20 17:12 UTC by LucasTonolli

2021-02-24 22:18 UTC, vantaBIack commented on Lucas_Tonolli/desafio_java/Superman.java
> +    public Superman(int dias,int forca_humano){
Utilizar Camel Case, "int forcaHumano". Há muita lógica dentro do construtor, este deveria servir apenas para instanciar o objeto. Deixando a lógica dentro do construtor, uma vez criado o objeto Superman os cálculos de força e visão não podem mais serem refeitos para aquele objeto, apenas instanciando um objeto novo. Sugiro separar os cálculos de força e visão em métodos próprios.

2021-02-24 22:19 UTC, vantaBIack commented on Lucas_Tonolli/desafio_java/Superman.java
> +    public double getdistancia_visao_calor(){
Utilizar Camel Case

2021-02-24 22:19 UTC, vantaBIack commented on Lucas_Tonolli/desafio_java/Superman.java
> +    public void setdistancia_visao_calor(double distancia_visao_calor){
Utilizar Camel Case

2021-02-24 22:19 UTC, vantaBIack commented on Lucas_Tonolli/desafio_java/Superman.java
> +        this.distanciaVisaoCalor = distancia_visao_calor;
Utilizar Camel Case

2021-03-04 19:43 UTC, rogtejada requested changes

2021-03-04 19:43 UTC, rogtejada commented on Lucas_Tonolli/desafio_java/Superman.java
> +    public void SuperPowerCalculator() {
Apenas a classe fica com letra maiúscula e o construtor, demais métodos e variáveis devem começar com letra minúscula

2021-03-04 20:20 UTC, rogtejada approved these changes
Bacana tua solução.

Uma dica, não é necessário colocar comentários em trechos do código autoexplicativos.
Comentário são interessantes quando tu tem fluxos complexos ou quer explicar o uso de determinada interface ou método
Ex
//Construtor

A ideia é que o código seja autoexplicativo, pensando nisso é legar darmos nomes claros pras variváveis e métodos. Se tiver interesse em ver um pouco mais sobre o assunto tu pode pesquisar sobre clean code

2021-03-04 20:21 UTC, merged