Desafio superhomem
ilegra/mais-pra-ti pull request #18
Opened 2021-02-20 23:09 UTC by BeahIF

Enviando a tarefa do cálculo da força do super-homem.

2021-02-24 22:20 UTC, vantaBIack commented on Bea/superhomem.java
> +public class superhomem{
Classes em Java devem começar com letra maiúscula

2021-03-04 19:38 UTC, rogtejada requested changes
Acredito que os dois des

2021-03-04 19:38 UTC, rogtejada commented on Bea/poo/Candidato.java
> +        //this.federacao = federacao;
remover código nao utilizado

2021-03-04 19:38 UTC, rogtejada commented on Bea/poo/Main.java
> +//        System.out.println(candidatos.get(0).getNumero());
remover código nao utilizado

2021-03-04 19:38 UTC, rogtejada commented on Bea/poo/Main.java
> +        ArrayList<Candidato> candidatos = new ArrayList<Candidato>();
Dar preferência pela interface List< Candidato>.
Assim quando tu quiser mudar o tipo de lista utilizado (exemplo LinkedList ao inves de ArrayList) nao tera impacto no teu código.
Isso é uma boa prática

2021-03-22 22:51 UTC, rogtejada approved these changes

2021-03-22 22:51 UTC, merged