incluindo desafio java
ilegra/mais-pra-ti pull request #20
Opened 2021-02-24 19:37 UTC by FelipeSimoes1

2021-02-24 23:07 UTC, rogtejada commented
Cara teu tema ficou show, porém tem alguns arquivos de banco de dados aparecendo nesse PR. Acredito que tu não tenha atualizado tua branch, consegue verificar pra mim.
Qualquer dificuldade ou duvida com isso pode me chamar

Outra coisa, é legal não commitar a pasta "out" nem a pasta ".idea", uma maneira de fazer isso é usar um arquivo chamado ".gitignore" assim ele diz pro git ignorar essas pastas e elas não aparecem no teu PR.

Segue a imagem:
![image](https://user-images.githubusercontent.com/42949854/109077864-8f5bb700-76db-11eb-9488-d55ca3ae4ac9.png)

2021-02-24 23:07 UTC, rogtejada requested changes
Cara teu tema ficou show, porém tem alguns arquivos de banco de dados aparecendo nesse PR. Acredito que tu não tenha atualizado tua branch, consegue verificar pra mim.
Qualquer dificuldade ou duvida com isso pode me chamar

Outra coisa, é legal não commitar a pasta "out" nem a pasta ".idea", uma maneira de fazer isso é usar um arquivo chamado ".gitignore" assim ele diz pro git ignorar essas pastas e elas não aparecem no teu PR.

Segue a imagem:
![image](https://user-images.githubusercontent.com/42949854/109077864-8f5bb700-76db-11eb-9488-d55ca3ae4ac9.png)

2021-02-25 16:54 UTC, FelipeSimoes1 commented
Eai Rodrigo, em relação aos arquivos de banco de dados que apareceram no PR, acredito que tenha sido por que eu reorganizei as pastas, criei uma pasta para o desafio de banco de dados e outra para o desafio de java e incluí seus respectivos arquivos.

Em relação a ter comitado pastas que não precisavam, eu fiquei em dúvida se comitava apenas o arquivo que tem o código ou todo o projeto e por isso acabei comitando tudo. Existe a possibilidade de eu incluir o arquivo ".gitignore" agora? Qual a melhor maneira de resolver esse problema? Obrigado.

2021-02-25 18:21 UTC, FelipeSimoes1 commented
Removi os arquivos desnecessários que já haviam sido comitados utilizando o comando **git rm -r --cached** e logo após inseri o arquivo .gitignore juntamente com os arquivos realmente necessários no pull request. Acredito que agora esteja em conformidade com o solicitado.

2021-02-25 20:06 UTC, rogtejada approved these changes

2021-02-25 20:07 UTC, merged