Adicionado Desafio Java Super Hero Power Calculator por Eliseu Brito
ilegra/mais-pra-ti pull request #22
Opened 2021-02-25 21:58 UTC by eliseusbrito

2021-02-28 22:27 UTC, rogtejada requested changes
Ficou muito boa tua solução, parabéns!
Deixei apenas um comentário ali pra colocar o modificador de acesso, é importante isso pra manter o encapsulamento (um dos pilares da orientação a objetos), ou seja expor apenas aquilo que for necessário da tua classe.
Uma dica no geral, arquivos ".class" e a pasta ".idea" poderiam ser deixados de fora do commit, uma maneira de resolver isso é usar um arquivo chamado ".gitignore" que avisa pro git ignorar esses caras. Isso é uma boa prática pra versionar(adicionar no github) apenas o essencial pra rodar o projeto. Caso se sinta confortável essa é uma melhoria legal de fazer.

2021-02-28 22:27 UTC, rogtejada commented on Eliseu_Brito/DesafioJavaSuperHeroPowerCalculator/src/dncsh/Calculator.java
> +    DecimalFormat df = new DecimalFormat("0.00");
adicionar o modificador de acesso nessas variáveis (private, public, ...). Acredito que nesse caso o ideal é elas serem private uma vez que nao devem ser acessadas de fora

2021-03-01 17:34 UTC, eliseusbrito commented on Eliseu_Brito/DesafioJavaSuperHeroPowerCalculator/src/dncsh/Calculator.java
> +    DecimalFormat df = new DecimalFormat("0.00");
Adicionado gitignore na pasta raiz do meu diretorio. Favor verificar se funcionou, não tenho certeza se assim funcionará ou se será necessário colocar um gitignore por projeto.

2021-03-02 00:28 UTC, rogtejada approved these changes

2021-03-02 00:28 UTC, merged