Adicionado Desafio Eleicao POO
ilegra/mais-pra-ti pull request #25
Opened 2021-03-02 01:00 UTC by eliseusbrito

Não consegui usar Interface e acabou não sendo necessário usar getters e setters. Até receber o retorno de vocês vou dar uma pesquisada sobre listas que vcs sugeriram no grupo para usar.

2021-03-04 19:26 UTC, rogtejada requested changes

2021-03-04 19:26 UTC, rogtejada commented on Eliseu_Brito/DesafioEleicaoPOO/src/br/eliseu/Deputado.java
> +    Eleicao candidato;
Adicionar modificador de acesso

2021-03-04 19:26 UTC, rogtejada commented on Eliseu_Brito/DesafioEleicaoPOO/src/br/eliseu/Eleicao.java
> +    Integer numeroCandidato;
Adicionar modificador de acesso

2021-03-18 11:00 UTC, eliseusbrito commented on Eliseu_Brito/DesafioEleicaoPOO/src/br/eliseu/Deputado.java
> +    Eleicao candidato;
Adicionado modificador conforme solicitado.

2021-03-18 11:00 UTC, eliseusbrito commented on Eliseu_Brito/DesafioEleicaoPOO/src/br/eliseu/Eleicao.java
> +    Integer numeroCandidato;
Adicionado modificador conforme solicitado.

2021-03-22 22:46 UTC, rogtejada approved these changes

2021-03-22 22:46 UTC, merged