Desafiopoo
ilegra/mais-pra-ti pull request #27
Opened 2021-03-03 00:04 UTC by brunostracke

2021-03-04 19:31 UTC, rogtejada requested changes

2021-03-04 19:31 UTC, rogtejada commented on Bruno Stracke/desafio_java/Kripto.java
> +    private int dias;
Acredito que esses arquivos sejam do desafio 1 correto? Tu esta fazendo todos na mesma branch?

2021-03-04 19:54 UTC, brunostracke commented on Bruno Stracke/desafio_java/Kripto.java
> +    private int dias;
São do desafio 01 sim. O desafio do SuperHomem eu fiz na branch main. Para os deputados eu criei uma branch específica.

2021-03-22 22:48 UTC, rogtejada approved these changes

2021-03-22 22:48 UTC, merged