Desafio poo
ilegra/mais-pra-ti pull request #35
Opened 2021-03-09 20:00 UTC by LucasTonolli

2021-03-10 02:24 UTC, rogtejada requested changes

2021-03-10 02:24 UTC, rogtejada commented on Lucas_Tonolli/Desafio_Orien_Obj/src/Candidato.java
> +public abstract class Candidato {
Pq aqui tu tem duas vezes a declaração da classe abstrata candidato? Vi que isso acontece tbm pra deputado estadual/federal o ideal é ter apenas uma vez isso

2021-03-10 12:37 UTC, LucasTonolli commented on Lucas_Tonolli/Desafio_Orien_Obj/src/Candidato.java
> +public abstract class Candidato {
É que antes atualizei, deve ter ficado os arquivos antigos e não vi.

2021-03-22 22:47 UTC, rogtejada approved these changes

2021-03-22 22:48 UTC, merged